name: build-wine

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: ./build.sh wine
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.pkg.tar.zst
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: ./build.sh wine wine-tkg-deb
      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.deb
